#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"
#include "funcs.h"

// add your tests here

TEST_CASE("Random Text Tests")
{
	CHECK(solve(encryptCaesar("The name funny bone comes from the humerus bone, which connects the shoulder to the elbow. However, that's not the source of the tingling sensation you feel when you bump your elbow just right. It's actually the result of the humerus bone coming into contact with the ulnar nerve, which is responsible for telling the brain about feelings in the ring and pinky fingers.", 5)) == "The name funny bone comes from the humerus bone, which connects the shoulder to the elbow. However, that's not the source of the tingling sensation you feel when you bump your elbow just right. It's actually the result of the humerus bone coming into contact with the ulnar nerve, which is responsible for telling the brain about feelings in the ring and pinky fingers.");
	CHECK(solve(encryptCaesar("The National Association of City Transportation Officials says that the average time spent waiting at a red light is 75 seconds, accounting for approximately 20 percent of all driving time. That's a whole lot of time doing nothing and just another reason to switch to public transportation.", 21)) == "The National Association of City Transportation Officials says that the average time spent waiting at a red light is 75 seconds, accounting for approximately 20 percent of all driving time. That's a whole lot of time doing nothing and just another reason to switch to public transportation.");
	CHECK(solve(encryptCaesar("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", 14)) == "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.");
	CHECK(solve(encryptCaesar("Trypophobia is the fear of closely-packed holes. Or more specifically, an aversion to the sight of irregular patterns or clusters of small holes or bumps.", 3)) == "Trypophobia is the fear of closely-packed holes. Or more specifically, an aversion to the sight of irregular patterns or clusters of small holes or bumps.");
	CHECK(solve(encryptCaesar("The heart of a shrimp is located in its head. They also have an open circulatory system, which means they have no arteries and their organs float directly in blood.", 24)) == "The heart of a shrimp is located in its head. They also have an open circulatory system, which means they have no arteries and their organs float directly in blood.");
	CHECK(solve(encryptCaesar("Avocados are a fruit, not a vegetable. They're technically considered a single-seeded berry, believe it or not.", 11)) == "Avocados are a fruit, not a vegetable. They're technically considered a single-seeded berry, believe it or not.");
}
